const $=id=>document.getElementById(id);
const labels={top:'TOP · เลนบน',jungle:'JUNGLE · ป่า',middle:'MID · เลนกลาง',bottom:'ADC · เลนล่าง',support:'SUPPORT · ซัพพอร์ต'};
let roster,thai,stats,champ='Ahri',lane,role='all',expanded={bad:false,good:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=id=>`https://ddragon.leagueoflegends.com/cdn/${roster.version}/img/champion/${id}.png`;
const thaiName=id=>thai.data[id]?.name??roster.data[id]?.name??id;
const aliases={Ahri:'อาห์รี อารี',Aatrox:'อาทร็อกซ์',Akali:'อาคาลิ อาคาลี',Ashe:'แอช',Annie:'แอนนี่',Yasuo:'ยาสุโอะ ยาสูโอ',Yone:'โยเนะ',Lux:'ลักซ์ ลักส์',Jinx:'จิงซ์ จิ๊งซ์',LeeSin:'ลีซิน',Zed:'เซด แซด',Darius:'ดาเรียส',Garen:'กาเรน',Teemo:'ทีโม',MasterYi:'มาสเตอร์ยี',MissFortune:'มิสฟอร์จูน',Ezreal:'เอซเรียล',Caitlyn:'เคทลิน',Vayne:'เวย์น',Lucian:'ลูเซียน',Sett:'เซตต์',Morgana:'มอร์กาน่า',Malphite:'มัลไฟต์',Thresh:'เธรช',Lulu:'ลูลู',Nami:'นามิ',Soraka:'โซราก้า',Sona:'โซน่า',Jhin:'จิน',Katarina:'คาตาริน่า',Riven:'ริเวน',Fiora:'ฟิโอร่า',Irelia:'ไอเรเลีย',Kaisa:'ไคซา ไคซ่า',Blitzcrank:'บลิตซ์แครงค์',MonkeyKing:'วูคอง',Braum:'บรอม',Nasus:'นาซัส',Veigar:'วีการ์',Vex:'เว็กซ์',Vladimir:'วลาดิเมียร์',Ziggs:'ซิกส์',Warwick:'วอร์วิค',Volibear:'โวลิแบร์'};
function renderRoster(){const query=$('search').value.toLowerCase().trim();const list=Object.values(roster.data).filter(c=>(role==='all'||stats.champions[c.id]?.lanes[role])&&(!query||`${c.name} ${c.id} ${thaiName(c.id)} ${thai.data[c.id]?.title??''} ${aliases[c.id]??''}`.toLowerCase().includes(query))).sort((a,b)=>a.name.localeCompare(b.name));$('result-count').textContent=`พบ ${list.length} แชมเปียน`;$('roster').innerHTML=list.length?list.map(c=>`<button class="champ-btn ${c.id===champ?'selected':''}" data-champ="${c.id}" aria-label="เลือก ${esc(c.name)}" aria-pressed="${c.id===champ}"><img src="${image(c.id)}" alt="" loading="lazy"><span>${esc(c.name)}</span></button>`).join(''):'<p class="empty">ไม่พบแชมเปียน ลองค้นหาชื่ออื่น</p>';}
function renderChampion(){const c=roster.data[champ],data=stats.champions[champ];const lanes=Object.keys(data?.lanes??{});if(!lanes.includes(lane))lane=lanes[0];expanded={bad:false,good:false};$('hero').style.backgroundImage=`url("https://ddragon.leagueoflegends.com/cdn/img/champion/splash/${c.id}_0.jpg")`;$('champ-name').textContent=c.name;$('champ-title').textContent=`${thaiName(champ)} · ${thai.data[champ]?.title??c.title}`;$('champ-tags').textContent=c.tags.join(' / ').toUpperCase();$('champ-key').textContent=`CHAMPION #${c.key}`;$('patch').textContent=data?.patch?`MATCHUP PATCH ${data.patch}`:'ยังไม่มีข้อมูลแพตช์';$('source-link').href=data.url;$('lanes').innerHTML=lanes.length?lanes.map(l=>`<button data-lane="${esc(l)}" class="${l===lane?'active':''}">${esc(labels[l]??l)}</button>`).join(''):'<span class="muted">ยังไม่มีข้อมูลตำแหน่ง</span>';renderMatchups();renderRoster();syncItemPlanner();}
function renderMatchups(){const rows=stats.champions[champ]?.lanes[lane]??[];const bad=rows.filter(x=>x.opponentWinRate>50).sort((a,b)=>b.opponentWinRate-a.opponentWinRate);const good=rows.filter(x=>x.opponentWinRate<50).sort((a,b)=>a.opponentWinRate-b.opponentWinRate);$('bad-sub').textContent=`${roster.data[champ].name} เสียเปรียบ · ${bad.length} คู่`;$('good-sub').textContent=`${roster.data[champ].name} ได้เปรียบ · ${good.length} คู่`;
for(const [side,list] of [['bad',bad],['good',good]]){const visible=expanded[side]?list:list.slice(0,6);$(side+'-list').innerHTML=visible.length?visible.map((r,i)=>{const c=roster.data[r.id];const wr=100-r.opponentWinRate;return `<a class="match-row" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer" aria-label="ดูสถิติ ${esc(roster.data[champ].name)} พบ ${esc(c.name)}"><span class="rank">${String(i+1).padStart(2,'0')}</span><img src="${image(c.id)}" alt="" loading="lazy"><span class="match-name">${esc(c.name)}<small>${esc(thaiName(c.id))}</small></span><span class="rate">${wr}%<span class="mini-bar"><span style="width:${wr}%"></span></span></span></a>`;}).join(''):'<p class="empty">ไม่มีคู่ที่เข้าเกณฑ์ในตำแหน่งนี้ ดูข้อมูลเพิ่มเติมจากต้นทางได้</p>';if(list.length>6)$(side+'-list').innerHTML+=`<button class="more" data-more="${side}">${expanded[side]?'แสดงน้อยลง':`ดูทั้งหมด ${list.length} คู่`}</button>`;}}
function choose(id){if(!roster.data[id])return;champ=id;lane=role==='all'?undefined:role;history.replaceState(null,'','#'+id);renderChampion();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!roster)return;if(b.dataset.champ)choose(b.dataset.champ);if(b.dataset.lane){lane=b.dataset.lane;expanded={bad:false,good:false};document.querySelectorAll('[data-lane]').forEach(x=>x.classList.toggle('active',x.dataset.lane===lane));renderMatchups();}if(b.dataset.role){role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x.dataset.role===role));renderRoster();}if(b.dataset.more){expanded[b.dataset.more]=!expanded[b.dataset.more];renderMatchups();}});
$('search').addEventListener('input',()=>roster&&renderRoster());window.addEventListener('hashchange',()=>choose(decodeURIComponent(location.hash.slice(1))));
async function load(){try{[roster,thai,stats]=await Promise.all(['champions.json','champions-th.json','matchups.json'].map(async f=>{const r=await fetch(f);if(!r.ok)throw Error(f);return r.json();}));$('count').textContent=Object.keys(roster.data).length;$('fetched').textContent='รวบรวมข้อมูลเมื่อ '+new Date(stats.fetchedAt).toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Bangkok'})+' • ชุดข้อมูลนี้ไม่อัปเดตสถิติอัตโนมัติ เปิดข้อมูลต้นทางเพื่อดูข้อมูลใหม่ล่าสุด';$('data-version').textContent='ROSTER '+roster.version;$('loading').hidden=true;$('content').hidden=false;const hash=decodeURIComponent(location.hash.slice(1));choose(roster.data[hash]?hash:'Ahri');initItemPlanner();}catch(e){$('loading').innerHTML='โหลดข้อมูลไม่สำเร็จ กรุณาลองอีกครั้ง <button id="retry">ลองใหม่</button>';$('retry').onclick=load;}}
load();
