let itemData,itemThai,plannerReady=false;
const threatLabels={healing:'ฮีล / ฟื้นฟูเลือดมาก',attacks:'ใช้การโจมตีปกติ',crit:'คริติคอล',shields:'มีโล่',cc:'CC ที่ลดเวลาด้วย Tenacity ได้',suppression:'Suppression',trueDamage:'มีดาเมจจริง'};
function resetItemResult(){$('item-result').hidden=true;$('item-status').textContent='เลือกคู่ต่อสู้แล้วกดคำนวณเพื่อดูคำแนะนำ';}
function syncItemPlanner(){if(!plannerReady)return;$('item-own').value=champ;fillPositions(lane);resetItemResult();}
const damageLabels={physical:'กายภาพ',magic:'เวท',mixed:'ผสม (กายภาพ + เวท)'};
function fillPositions(preferred=$('item-position').value){const id=$('item-own').value;const available=Object.keys(labels);const defaultLane=Object.keys(stats.champions[id]?.lanes??{})[0]??'middle';$('item-position').innerHTML=available.map(l=>`<option value="${l}">${labels[l]}</option>`).join('');$('item-position').value=available.includes(preferred)?preferred:defaultLane;$('item-profile').value=RiftItems.inferProfile(roster.data[id],$('item-position').value);}
function fillThreats(){const c=roster.data[$('item-enemy').value];if(!c){$('item-damage').value='เลือกคู่ต่อสู้ก่อน';for(const key of Object.keys(threatLabels))$('threat-'+key).checked=false;resetItemResult();return;}const t=RiftItems.inferThreats(c);$('item-damage').value=damageLabels[t.damage];for(const key of Object.keys(threatLabels))$('threat-'+key).checked=t[key];resetItemResult();}
async function initItemPlanner(){try{[itemData,itemThai]=await Promise.all(['items.json','items-th.json'].map(async p=>{const r=await fetch(p);if(!r.ok)throw Error(p);return r.json();}));
const options=Object.values(roster.data).sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(thai.data[c.id]?.title??'')}</option>`).join('');$('item-own').innerHTML=options;$('item-enemy').innerHTML='<option value="">เลือกตัวที่ต้องการแก้ทาง</option>'+options;$('item-profile').innerHTML=Object.entries(RiftItems.profileLabels).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('');$('item-threats').innerHTML=Object.entries(threatLabels).map(([k,v])=>`<label><input type="checkbox" id="threat-${k}"> ${v}</label>`).join('');
plannerReady=true;syncItemPlanner();$('item-submit').disabled=false;$('item-status').textContent='เลือกคู่ต่อสู้แล้วกดคำนวณเพื่อดูคำแนะนำ';
$('item-own').addEventListener('change',()=>{fillPositions();resetItemResult();});$('item-position').addEventListener('change',()=>{$('item-profile').value=RiftItems.inferProfile(roster.data[$('item-own').value],$('item-position').value);resetItemResult();});$('item-enemy').addEventListener('change',fillThreats);$('item-form').addEventListener('input',resetItemResult);$('item-form').addEventListener('submit',e=>{e.preventDefault();calculateItems();});$('item-reset-threats').addEventListener('click',fillThreats);
}catch(e){$('item-status').textContent='โหลดข้อมูลไอเทมไม่สำเร็จ รายการคู่ต่อสู้ด้านบนยังใช้งานได้';$('item-retry').hidden=false;$('item-retry').onclick=()=>{$('item-retry').hidden=true;initItemPlanner();};}}
function itemCard(row,index){const i=itemData.data[row.id],t=itemThai.data[row.id];return `<article class="item-card"><span class="item-step">${index+1}</span><img src="https://ddragon.leagueoflegends.com/cdn/${itemData.version}/img/item/${esc(i.image.full)}" alt="" loading="lazy"><div><h4>${esc(i.name)}</h4>${t?.name!==i.name?`<span class="item-thai">${esc(t?.name??'')}</span>`:''}<span class="item-price">${i.gold.total.toLocaleString()} G</span><p>${esc(row.reason)}</p></div></article>`;}
function calculateItems(){const own=roster.data[$('item-own').value],enemy=roster.data[$('item-enemy').value];if(!enemy){$('item-status').textContent='กรุณาเลือกตัวที่ต้องการแก้ทางก่อน';$('item-enemy').focus();return;}if(own.id===enemy.id){$('item-status').textContent='กรุณาเลือกคู่ต่อสู้คนละตัวกับตัวที่เราเล่น';return;}const threat={damage:RiftItems.inferThreats(enemy).damage,...Object.fromEntries(Object.keys(threatLabels).map(k=>[k,$('threat-'+k).checked]))};const profile=$('item-profile').value,position=$('item-position').value;const result=RiftItems.plan({own,enemy,profile,position,threat,items:itemData.data});
$('item-result-title').textContent=`${own.name} พบ ${enemy.name}`;$('item-result-meta').textContent=`${labels[position]} • ${RiftItems.profileLabels[profile]} • ไอเทม ${itemData.version}`;$('item-portraits').innerHTML=`<img src="${image(own.id)}" alt="${esc(own.name)}"><span>VS</span><img src="${image(enemy.id)}" alt="${esc(enemy.name)}">`;
$('item-start').innerHTML=itemCard({id:result.starter,reason:position==='jungle'?'ไอเทมเริ่มต้นสำหรับป่า ต้องใช้ Smite; เลือกสัตว์เลี้ยงตามสไตล์การเล่นได้':position==='support'?'ไอเทมเริ่มต้นซัพพอร์ต ทำเควสต์และเลือกอัปเกรดตามหน้าที่':'ไอเทมเริ่มต้นตามสายที่เลือก ปรับเป็น Doran’s Shield หากต้องรับ poke หนัก'},0);
$('item-early').innerHTML=result.early.length?result.early.map(itemCard).join(''):'<p class="empty">ยังไม่มีชิ้นส่วนแก้ทางที่จำเป็นเป็นพิเศษ เริ่มจากชิ้นส่วนของไอเทมหลัก</p>';
$('item-order').innerHTML=result.order.map(itemCard).join('');$('item-counter').innerHTML=result.counter.length?result.counter.map((x,i)=>itemCard(x,i)).join(''):'<p class="empty">ใช้บิลด์หลักเป็นฐาน แล้วปรับตามดาเมจของทั้งทีมศัตรู</p>';$('item-warnings').innerHTML=result.warnings.map(x=>`<li>${esc(x)}</li>`).join('');$('item-status').textContent='คำนวณแล้ว — ปรับเงื่อนไขด้านบนและคำนวณใหม่ได้';$('item-result').hidden=false;}
