/* Rule-based guidance, not a simulation or matchup win-rate model. */
(function(root){
const groups={
 enchanter:'Janna Karma Lulu Milio Nami Renata Soraka Sona Yuumi Ivern',
 supportTank:'Alistar Braum Leona Nautilus Rell Taric Thresh Blitzcrank',
 tank:'Amumu Chogath DrMundo Galio KSante Malphite Maokai Nunu Ornn Rammus Sejuani Shen Sion Skarner Zac',
 onhit:'Akshan Belveth Kalista Kaisa KogMaw MasterYi Quinn Varus Vayne Viego Kayle Kindred Teemo',
 crit:'Aphelios Ashe Caitlyn Corki Draven Jhin Jinx Lucian MissFortune Nilah Samira Sivir Smolder Tristana Twitch Xayah Yasuo Yone Yunara Zeri',
 assassinAD:'Briar Khazix Naafiri Nocturne Pyke Qiyana Rengar Shaco Talon Zed',
 fighterAP:'Diana Ekko Elise Evelynn Fizz Gragas Gwen Lillia Mordekaiser Nidalee Rumble Shyvana Singed Sylas Vladimir Akali Katarina Kennen',
 fighterAD:'Aatrox Ambessa Camille Darius Fiora Gangplank Garen Gnar Graves Hecarim Illaoi Irelia JarvanIV Jax Jayce Kled LeeSin MonkeyKing Olaf Pantheon Poppy RekSai Renekton Riven Sett Trundle Tryndamere Udyr Urgot Vi Volibear Warwick XinZhao Yorick',
 supportAP:'Bard Seraphine Zilean',
 mage:'Ahri Anivia Annie AurelionSol Aurora Azir Brand Cassiopeia Hwei Heimerdinger Karthus Kassadin Leblanc Lissandra Lux Malzahar Mel Neeko Orianna Ryze Swain Syndra Taliyah TwistedFate Veigar Velkoz Vex Viktor Xerath Ziggs Zoe Zyra',
};
const groupSets=Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,new Set(v.split(' '))]));
const profileLabels={mage:'เมจ AP',fighterAP:'ไฟต์เตอร์ / แอสซาซิน AP',fighterAD:'ไฟต์เตอร์ AD',assassinAD:'แอสซาซิน AD',crit:'แครี่คริติคอล',onhit:'โจมตีต่อเนื่อง / On-hit',tank:'แทงค์',enchanter:'ซัพพอร์ตฮีล / โล่',supportTank:'ซัพพอร์ตแทงค์',supportAP:'ซัพพอร์ต AP',ezreal:'Ezreal · AD สกิล'};
const cores={mage:['6655','3089','3135','4645'],fighterAP:['4633','3115','3089','3135'],fighterAD:['3078','6610','3053','3071'],assassinAD:['3142','6692','6694','3026'],crit:['6676','3031','3094','3036'],onhit:['3153','3124','3085','3026'],tank:['3068','6665','3083','3065'],enchanter:['6617','3107','3504','3222'],supportTank:['3190','3109','3050','3107'],supportAP:['4005','3116','3107','3137'],ezreal:['3004','3078','6694','3074']};
const overrides={Akali:['3152','4645','3089','3135'],Katarina:['3115','4645','3089','3135'],Gragas:['3100','3152','3089','3135'],Sylas:['3152','3100','3089','3135'],Ahri:['3118','3089','3135','4645'],Anivia:['6657','3003','3135','3089'],AurelionSol:['3116','6653','3135','3089'],Azir:['3115','3089','3135','4645'],Brand:['6653','3116','3135','3089'],Cassiopeia:['3003','3116','6653','3135','3089'],Diana:['3115','4633','3089','3135'],Ekko:['3100','3089','3135','4645'],Evelynn:['3100','3089','3135','4645'],Fizz:['3100','3089','3135','4645'],Galio:['3152','3102','3068','6665'],Gwen:['3115','4633','3089','3135'],Jhin:['6676','3031','3094','3036'],Kaisa:['6672','3124','3115','3026'],Kassadin:['6657','3003','3089','3135'],Kayle:['3115','3089','3135','3124'],Kennen:['3152','3089','3135','4645'],Lillia:['6653','4633','3089','3135'],Malzahar:['6653','3116','3135','3089'],Mordekaiser:['3116','6653','4633','3065'],Nidalee:['3100','3152','3089','3135'],Pyke:['6694','3142','3026','6692'],Rumble:['6653','3152','3135','3089'],Ryze:['3003','6657','3089','3135'],Singed:['3116','6653','3065','3089'],Swain:['6653','3116','3065','3135'],Teemo:['3115','6653','3089','3135'],TwistedFate:['6657','3100','3094','3089'],Varus:['3153','3124','3085','3026'],Viego:['3153','6610','3053','3026'],Vladimir:['4633','3089','3135','3102'],Yasuo:['3153','6673','3031','6333'],Yone:['3153','6673','3031','6333'],Zyra:['6653','3116','3135','3089'],Senna:['3071','3094','3031','3033']};
const threatGroups={
 magic:'Ahri Akali Amumu Anivia Annie AurelionSol Aurora Azir Bard Brand Cassiopeia Chogath Diana Ekko Elise Evelynn Fiddlesticks Fizz Galio Gragas Gwen Hwei Heimerdinger Ivern Janna Karma Karthus Kassadin Katarina Kennen Leblanc Lillia Lissandra Lulu Lux Malzahar Maokai Mel Milio Mordekaiser Morgana Nami Neeko Nidalee Nunu Orianna Rumble Ryze Seraphine Singed Sona Soraka Swain Sylas Syndra Taliyah Teemo Veigar Velkoz Vex Viktor Vladimir Xerath Yuumi Zac Ziggs Zilean Zoe Zyra',
 mixed:'Corki Ezreal Jax Kaisa Kayle KogMaw Shen Shyvana Skarner Smolder Taric Tristana Udyr Varus Volibear Warwick Yone Yunara',
 healing:'Aatrox Briar Darius DrMundo Fiora Fiddlesticks Gwen Illaoi Irelia Maokai MasterYi Milio Mordekaiser Nami Nasus Nidalee Nilah Nunu Olaf Renekton Rengar Samira Senna Seraphine Sona Soraka Swain Sylas Taric Trundle Vladimir Volibear Warwick XinZhao Yuumi Zac',
 attacks:'Warwick XinZhao Briar Fiora Olaf Darius Renekton Rengar Sett Volibear Akshan Aphelios Ashe Belveth Caitlyn Corki Draven Ezreal Irelia Jax Jhin Jinx Kalista Kaisa Kayle Kindred KogMaw Lucian MasterYi MissFortune Nasus Nilah Nocturne Quinn Samira Senna Sivir Smolder Teemo Tristana Trundle Tryndamere Twitch Varus Vayne Viego Xayah Yasuo Yone Yunara Zeri',
 crit:'Aphelios Ashe Caitlyn Draven Jhin Jinx Lucian Nilah Samira Sivir Tristana Tryndamere Xayah Yasuo Yone Yunara Zeri',
 shields:'Ambessa Blitzcrank Ivern Janna Karma Kaisa KSante LeeSin Lulu Lux Milio Mordekaiser Morgana Nautilus Orianna Rell Riven Seraphine Sett Shen Sion Skarner Sona TahmKench Taric Udyr Viktor Volibear Yuumi',
 cc:'Ahri Amumu Anivia Annie Ashe AurelionSol Bard Brand Braum Caitlyn Cassiopeia Elise Fiddlesticks Galio Hwei Ivern Janna Jax Jhin Kennen Leona Lissandra Lulu Lux Maokai Morgana Nami Neeko Pantheon Poppy Renekton Riven Sejuani Seraphine Shen Sona Swain Syndra Taric Thresh TwistedFate Udyr Veigar Vex Viktor Xerath Zilean Zoe Zyra',
 suppression:'Malzahar Warwick',
 trueDamage:'Belveth Camille Chogath Darius Fiora Gangplank Gwen KogMaw KSante Lillia MasterYi Olaf Pyke RekSai Sett Smolder Vayne Velkoz',
};
const threats=Object.fromEntries(Object.entries(threatGroups).map(([k,v])=>[k,new Set(v.split(' '))]));
function inferProfile(c,position){if(c.id==='Ezreal')return 'ezreal';if(position==='support'){if(groupSets.tank.has(c.id)||groupSets.fighterAD.has(c.id))return 'supportTank';if(groupSets.mage.has(c.id))return 'supportAP';}for(const [k,s] of Object.entries(groupSets))if(s.has(c.id))return k;if(c.id==='Senna')return 'crit';if(c.tags.includes('Marksman'))return 'crit';if(c.tags.includes('Mage'))return 'mage';if(c.tags.includes('Tank'))return 'tank';return 'fighterAD';}
function inferThreats(c){return {damage:threats.magic.has(c.id)?'magic':threats.mixed.has(c.id)?'mixed':'physical',...Object.fromEntries(Object.entries(threats).filter(([k])=>!['magic','mixed'].includes(k)).map(([k,s])=>[k,s.has(c.id)]))};}
function plan({own,enemy,profile,position,threat,items}){
const ap=['mage','fighterAP','supportAP'].includes(profile)||['Kayle','Teemo'].includes(own.id)&&profile==='onhit';const tank=['tank','supportTank'].includes(profile);const support=['enchanter','supportTank','supportAP'].includes(profile);const ad=!ap&&!tank&&!support;const warnings=[];const counter=[];const early=[];
const available=id=>{const i=items[id];return i&&i.maps?.['11']&&i.gold.purchasable&&Number(id)<10000};
const add=(arr,id,reason)=>{if(available(id)&&!arr.some(x=>x.id===id))arr.push({id,reason});};
if(threat.healing){if(tank&&threat.attacks){add(early,'3076','ซื้อเมื่อต้องรับการโจมตีปกติจากตัวที่ฮีล: ลดการฮีลเฉพาะผู้ที่โจมตีคุณ');add(counter,'3075','เพิ่มเกราะและลดการฮีลของศัตรูที่โจมตีปกติใส่คุณ');}else if(ap||profile==='enchanter'){add(early,'3916','ชิ้นส่วนลดการฮีลเมื่อทำดาเมจเวท เก็บไว้ก่อนโดยยังไม่ต้องรีบอัปเกรด');if(ap)add(counter,'3165','ลดการฮีลเมื่อคุณทำดาเมจเวท');else warnings.push('ซัพพอร์ตฮีล: ซื้อ Oblivion Orb เฉพาะเมื่อทำดาเมจเวทใส่เป้าหมายได้ต่อเนื่อง ให้เพื่อนที่ติดผลได้ง่ายรับหน้าที่ลดฮีลแทนได้');}else if(!tank){add(early,'3123','ลดการฮีลเมื่อทำดาเมจกายภาพ ไม่จำเป็นต้องรีบอัปเกรดเต็มชิ้น');add(counter,['crit','onhit'].includes(profile)?'3033':'6609','ลดการฮีลด้วยดาเมจกายภาพ เลือกเมื่อเป้าหมายฟื้นเลือดมาก');}if(tank&&!threat.attacks)warnings.push('Bramble Vest ไม่ติดลดฮีลหากเป้าหมายไม่โจมตีปกติใส่คุณ ให้ผู้ทำดาเมจในทีมรับหน้าที่ลดฮีล');}
if(threat.suppression){add(early,'3140','ใช้ Active แก้ Suppression ของ Malzahar หรือ Warwick; ไม่แก้ Knock-up');if(ad)add(counter,'3139','อัปเกรด QSS เป็นไอเทม AD ที่มี Active ล้าง CC');else warnings.push('เก็บ QSS เป็นชิ้นส่วนเฉพาะกิจหากถูกล็อกเป็นเป้าหมายหลัก ไม่จำเป็นต้องอัปเกรดเป็น Mercurial สำหรับสาย AP/แทงค์');}
if(threat.damage==='magic'||threat.damage==='mixed'){if(tank)add(counter,'2504','ต้านเวทและโล่รับดาเมจเวท เหมาะเมื่อต้องยืนรับเวท');else if(ap)add(counter,'3102','AP + ต้านเวท และ Spell Shield สำหรับรับสกิลเปิดของคู่ต่อสู้');else if(ad)add(counter,'3156','AD + ต้านเวท พร้อมโล่เมื่อเลือดต่ำจากดาเมจเวท');else add(counter,'3190','เกราะและต้านเวท พร้อมโล่ให้ทีม ใช้รับจังหวะดาเมจพร้อมกัน');}
if(threat.damage==='physical'||threat.damage==='mixed'){if(tank)add(counter,threat.crit?'3143':threat.attacks?'3110':'3068',threat.crit?'ลดดาเมจคริติคอลและเพิ่มเกราะ':threat.attacks?'เพิ่มเกราะและลดความเร็วโจมตีของศัตรูใกล้ตัว':'เกราะและเลือดสำหรับรับดาเมจกายภาพ');else if(ap)add(counter,'3157','เกราะ + AP; ใช้ Stasis หลบจังหวะคอมโบหรือดาเมจระเบิด');else if(profile==='fighterAD')add(counter,'6333','เกราะและหน่วงดาเมจบางส่วน ช่วยไฟต์เตอร์ยืนสู้ต่อ');else if(ad)add(counter,'3026','เกราะและการฟื้นคืนชีพสำหรับจังหวะที่ถูกล้วง');else add(counter,'3190','โล่ป้องกันเพื่อนร่วมทีมในจังหวะโดนเปิด');}
if(threat.shields){if(profile==='assassinAD')add(counter,'6695','ลดโล่ของเป้าหมาย เหมาะกับสาย AD เจาะเกราะ');else warnings.push('เป้าหมายมีโล่: ประสานกับตัว AD เจาะเกราะในทีมให้ออก Serpent’s Fang; ไม่ควรทิ้งบิลด์หลักเพื่อซื้อในสาย AP/ซัพพอร์ต');}
if(threat.trueDamage)warnings.push('เป้าหมายมีดาเมจจริง: เกราะและต้านเวทไม่ลดส่วนนั้น โดยเฉพาะดาเมจจริงตาม % เลือด ให้เน้นหลบสกิลและจัดตำแหน่ง');
if(threat.cc)warnings.push('Tenacity ลดระยะเวลา CC บางชนิด ไม่ลด Knock-up หรือ Suppression');
const noMana=new Set('Aatrox Akali Ambessa Briar DrMundo Garen Gnar Katarina Kennen Kled LeeSin Mordekaiser RekSai Renekton Rengar Riven Rumble Sett Shen Shyvana Tryndamere Viego Vladimir Yasuo Yone Zac'.split(' '));if(noMana.has(own.id)){const x=counter.find(x=>x.id==='3110');if(x){x.id='3143';x.reason='เลือกเกราะและเลือดแทน Frozen Heart เพราะตัวที่เล่นไม่ใช้มานา';}}
const boots=own.id==='Cassiopeia'?null:threat.attacks&&threat.damage!=='magic'?'3047':threat.cc?'3111':tank?'3111':ap?'3020':support?'3158':'3006';
let core=(overrides[own.id]&&!['supportAP','supportTank','enchanter'].includes(profile)&&inferProfile(own,position)===profile?overrides[own.id]:cores[profile])??cores.mage;core=core.filter(available);if(profile==='tank'&&threat.damage==='magic'&&core[0]==='3068')core=['6664',...core.slice(1)];
if(counter.some(x=>['3033','6694'].includes(x.id)))core=core.filter(x=>!['3036','6694','3033','3071'].includes(x));if(counter.some(x=>x.id==='3156'))core=core.filter(x=>!['3053','6673'].includes(x));
if(profile==='onhit'&&['Kayle','Teemo'].includes(own.id))core=overrides[own.id];
const order=[];const coreReason='ไอเทมหลักตามสายที่เลือก รักษาดาเมจหรือหน้าที่ของตัวที่เล่น';if(core[0])add(order,core[0],coreReason);if(boots)add(order,boots,boots==='3047'?'ลดดาเมจจากการโจมตีปกติและเพิ่มเกราะ':boots==='3111'?'ต้านเวทและ Tenacity สำหรับ CC ที่ลดระยะเวลาได้':'รองเท้าให้ค่าสถานะตามสายที่เล่น');
for(const x of counter.slice(0,2))add(order,x.id,x.reason);for(const id of core.slice(1))if(order.length<6)add(order,id,coreReason);
const fallback=ap?['3089','3135','4645','3157']:tank?['3083','3065','6665','3143']:support?['3107','3190','3222','3109']:['3026','3074','3071','3153'];for(const id of fallback)if(order.length<6)add(order,id,coreReason);
if(position==='support'){order.splice(5);const upgrade=profile==='enchanter'?'3870':profile==='supportTank'?'3869':profile==='supportAP'?'3871':'3877';add(order,upgrade,'อัปเกรดจากเควสต์ซัพพอร์ต ไม่ใช่ไอเทมที่ซื้อเต็มชิ้นเพิ่ม; ใช้หนึ่งช่องในบิลด์');} const starter=position==='jungle'?'1102':position==='support'?'3865':tank?'1054':ap||profile==='enchanter'?'1056':'1055';
warnings.push('ลำดับนี้เป็นแนวทางตามคุณสมบัติไอเทมและสายที่เลือก ไม่ใช่บิลด์จากสถิติของคู่นี้ ปรับตามทั้งทีมศัตรู เงิน และสถานการณ์');if(early.some(x=>x.id==='3140')&&order.length===6)warnings.push('หากเก็บ QSS แยกต่างหาก ให้แทนไอเทมท้ายบิลด์หนึ่งช่อง; ห้ามนับเป็นช่องที่ 7');
return {starter,early,order,counter,warnings};}
root.RiftItems={profileLabels,inferProfile,inferThreats,plan};
})(typeof window!=='undefined'?window:globalThis);

